name: basic_social_media_app
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.1.1 <4.0.0"

dependencies:
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5

  firebase_core: ^2.21.0
  firebase_auth: ^4.12.1
  cloud_firestore: ^4.12.2
  firebase_storage: ^11.5.0

  flutter:
    sdk: flutter
    
  email_validator: ^2.1.17
  flutter_screenutil: ^5.9.0
  go_router: ^12.0.1
  google_fonts: ^6.1.0
  get_it: ^7.6.4
  shared_preferences: ^2.2.2
  cached_network_image: ^3.3.0
  image_picker: ^1.0.4
  path: ^1.8.3
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
